[build]
  publish = "./dist/"
  command = "mkdir bin && export PATH=\"/opt/build/repo/bin:$PATH\" && echo $PATH && curl https://static.lamdera.com/bin/linux/lamdera -o bin/lamdera && chmod a+x bin/lamdera &&  && lamdera --version && cd elm-pages && git submodule update --init --recursive && npm i && cd .. && npm i && export ELM_HOME=\"$NETLIFY_BUILD_BASE/cache/elm\" && npm run build"
