[build]
  publish = "./dist/"
  command = "git submodule update --init --recursive && mkdir bin && export PATH=\"/opt/build/repo/bin:$PATH\" && curl https://static.lamdera.com/bin/linux/lamdera -o bin/lamdera && chmod a+x bin/lamdera && export ELM_HOME=\"$NETLIFY_BUILD_BASE/cache/elm\" && npm i -g elm && npm run build"
